apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - target:
      kind: CatalogSource
      name: operatorhubio-catalog
    patch: |-
      - op: replace
        path: /spec/image
        value: localhost:5000/operatorhubio/catalog:0.1.0