- op: replace
  path: /spec/sourceType
  value: configmap

- op: add
  path: /spec/configMap
  value: operator-catalog

- op: remove
  path: /spec/image

- op: remove
  path: /spec/grpcPodConfig

- op: remove
  path: /spec/updateStrategy